### ISSUE TITLE
Incompatible with Create mod

### ISSUE THREAD

**Issue by Fyoncle** [Noxcrew/noxesium#68] opened 2024-05-29 19:50 UTC
yeah, it is.

**Comment by Aeltumn** [comment] 2024-05-29 20:03
Could you provide additional details on what features of Noxesium and/or Create are being broken? Is there a crash on start-up?

**Comment by Fyoncle** [comment] 2024-05-29 20:04
Yeah, just crash.

**Comment by Aeltumn** [comment] 2024-05-29 20:05
And which version of Noxesium & Create that you are using.

**Comment by Fyoncle** [comment] 2024-05-29 20:06
> And which version of Noxesium & Create that you are using.

Noxesium Latest at 1.20.1 Fabric, and latest Create

**Comment by Aeltumn** [comment] 2024-05-29 20:06
Noxesium for 1.20.1 has a number of known compatibility issues that have since been fixed. It would be more relevant to test if these compatibility issues still exist on 1.20.6.

**Comment by Aeltumn** [comment] 2024-05-29 20:08
If you have the crash report I can confirm whether the issue should be fixed in the latest version or not.

**Comment by Fyoncle** [comment] 2024-05-29 20:09
I don't have crash report at the moment, sorry.

**Comment by Aeltumn** [comment] 2024-05-29 20:10
Then I'll close it for now, if you have a crash report on the latest versions of Noxesium and Create it's something I can investigate further. Otherwise it's likely just a past issue that's nosw fixed.

**Closed by Aeltumn** 2024-05-29 20:10 UTC
Labels: wontfix

**Comment by Fyoncle** [comment] 2024-06-04 23:39
> Member

What known incompatibilites also? which mods?
