### ISSUE TITLE
Noxesium not detected on 1.20.4

### ISSUE THREAD

**Issue by osfanbuff63** [Noxcrew/noxesium#49] opened 2024-03-07 22:29 UTC
On Minecraft 1.20.4, Noxesium is not detected by MCC Island, so the Player Head Visibility setting is not toggleable. This is especially an issue because the newest working version was 1.20.2, but that version was dropped recently. Reproducing should be self-explanatory - get an instance of Minecraft 1.20.4 with Noxesium and notice that you can't check that setting.

I think this is possibly related to AsoDesu/IslandUtils#115 as that mod uses Noxesium to detect game events. As a result, I believe this is more likely to be a Noxesium issue than an MCCI issue, so I filed it here instead of on the forums.

**Comment by Aeltumn** [comment] 2024-03-08 15:21
It's being caused by weirdness with the configuration phase. Working on figuring out how exactly it all works between client, server, proxy and viaversion support for it.

**Comment by Aeltumn** [comment] 2024-04-06 21:20
Should be resolved in MCC Island's next update.

**Closed by Aeltumn** 2024-04-06 21:20 UTC
