### ISSUE TITLE
smooth lightning looks weird 

### ISSUE THREAD

**Issue by Silver0902** [Noxcrew/noxesium#91] opened 2024-08-10 19:56 UTC
i feel like the smooth lighning option in minecraft doesnt work with noxesium, atleast it looks like it

**Comment by Aeltumn** [comment] 2024-08-10 20:10
Could you elaborate on what you are talking about? Could you attach some screenshots of what you are seeing and what settings you are using?

**Comment by Silver0902** [comment] 2024-08-10 20:17
![grafik](https://github.com/user-attachments/assets/c8fe0453-5c2d-4be3-9c0e-d367d9f44677)

Normally the light should fade from block to block if smooth lightning is enabled, here you can see the hoppers having different ligtlevels with no fading to each other. The same is without shaders, just not as extreme. In summary its just about smooth lightning which just lets light smootly fade from block to block, which doesnt seem to work on some blocks

**Comment by Silver0902** [comment] 2024-08-10 20:20
![grafik](https://github.com/user-attachments/assets/701972e0-9c30-4080-b661-27e89fc3f1db)

Here an extreme example with the complementary reimagined shader, the blocks behind the glass just turn into the glass colors, this only happens with noxesium

**Comment by Aeltumn** [comment] 2024-08-10 21:35
Could you send the entire list of mods you are using? (including versions)

**Comment by Silver0902** [comment] 2024-08-10 21:42
uhm sorry i am using lunar client which recently added your mod into it, i dont think you can really see what mods they use

**Comment by Silver0902** [comment] 2024-08-10 21:43
![grafik](https://github.com/user-attachments/assets/811640c1-9bea-435a-ab41-9fff720e475e)

I have some custom ones added to it which you can see here, but there are more implemented into the client

**Comment by Silver0902** [comment] 2024-08-10 21:53
also iris 1.7.2

**Comment by Aeltumn** [comment] 2024-12-10 14:55
I cannot recreate this and cannot find any reason why this would be caused by Noxesium. Going to close it for now, please let me know if you can still recreate this on the latest version with only Noxesium and Fabric installed.

**Closed by Aeltumn** 2024-12-10 14:55 UTC
Labels: investigate
