### ISSUE TITLE
Forced disconnect when trying to join servers

### ISSUE THREAD

**Issue by derNiklaas** [Noxcrew/noxesium#99] opened 2024-09-19 16:46 UTC
![image](https://github.com/user-attachments/assets/d022766e-0a9b-45e6-bd69-f4c5aa3b6705)

Disconnect error: https://mclo.gs/nSymddN

Steps to reproduce:
1. Join ``timolia.de``
2. Try to join ``Jump World``
3. Get disconnected

Versions:
Minecraft 1.21.1
Noxesium 2.3.0+3bbfed9

**Comment by derNiklaas** [comment] 2024-09-19 16:48
I've also seen other people report this with wynncraft or hoplite, but I personally wasn't able to reproduce it there

**Comment by Cactooose** [comment] 2024-09-20 10:01
Yeah I have this exact same issue with my modpack, when you try to join any minigames server and then tap some minigame, normally you would just be teleported there, but with Noxesium it gives you an error🧻

**Comment by Aeltumn** [comment] 2024-09-20 21:47
Duplicate of #97.

**Closed by Aeltumn** 2024-09-20 21:47 UTC
